### ISSUE TITLE
Make error: target doesn't contain pattern character (%)

### ISSUE THREAD

**Issue by mawuli** [hgfischer/gomk#4]
I''m running on Mac OS X Yosemite 10.10.2 and I get an error when I run the Make command.

```bash
$ make 
$ go.mk:141: *** target pattern contains no `%'.  Stop.
```
Line 141 contains ```$(PRESENT)   : ; @go get -v golang.org/x/tools/cmd/present```, but I don't know how to go about this. I tried both Make versions 3.81 and 4.1 and the error still persists.

Thanks!

**Comment by hgfischer** [comment]
The project you are using it is open source? If so, can you send me the address so that I can test on my machine?

I'm using Linux Mint, based on Ubuntu 14.04 LTS, and GNU make 3.81 and I have no issues.

Also, can you send the output of `make printvars`?

**Comment by mawuli** [comment]
No, the project is not open source. ```make printvars``` also gives the same error :(

I'll try it on a Linux machine tomorrow.

Thanks!

**Comment by hgfischer** [comment]
I don't have a Mac to test it, so I need your help to fix it.

Maybe is something related to variable initialization.

Can you paste the output of `go env` here?

**Comment by mawuli** [comment]
```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mawuli/.go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by mawuli** [comment]
Fixed by setting the GOBIN variables: ```$ export GOBIN="$GOPATH/bin"```

**Comment by hgfischer** [comment]
Hi @mawuli 

I finally could reproduce the error and fix the problem. Your last comment helped! Thanks!

**Comment by mawuli** [comment]
Nice!
